version: 2
sources:
  - name: my_src
    schema: wrk_training
    tables:
      - name: src_population
        identifier: world_population
        loaded_at_field: edh_rec_cre_ts
        freshness: 
          error_after:
            count: 365
            period: day
          warn_after:
            count: 365
            period: day         
      - name: tgt_population
        identifier: dim_mart_world_population
      - name: tgt_population_typ1
        identifier: dim_mart_world_population_typ1
      - name: cntry_lkp
        identifier: wrk_mart_country_code_lookup


